services: 
  react-native-app:
    container_name: Golfbud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./Source:/Source
      - /Source/node_modules
    stdin_open: true
    tty: true
